checks:
  javascript: true
filter:
  excluded_paths:
    - test/*
    - node_modules/*
    - build/*
    - docs/*

build:
  environment:
    node: 8.1.0

  dependencies:
    before:
      - npm install -g grunt-cli

  tests:
    override:
      -
        command: 'grunt'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'
