checks:
  javascript: true
filter:
  excluded_paths:
    - test/*
    - node_modules/*
    - build/*
    - docs/*

build:

  dependencies:
    before:
      - export LATEST=$(nvm ls-remote | tail -1)
      - nvm install $LATEST
#      - nvm use $LATEST
      - npm install -g grunt-cli

  tests:
    override:
      -
        command: 'grunt'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'
